apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/

configMapGenerator:
  - name: fake-server-conf
    files:
      - fake.conf

patchesStrategicMerge:
  - ngix-deployment.yaml
  - ngix-service.yaml