apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      volumes:
        - name: fake-server-conf
          configMap:
            name: fake-server-conf
      containers:
        - name: nginx
          image: nginx:1.14.2
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/xxxxx

          env:
            - name: XXX
              value: cccc
          volumeMounts:
            - mountPath: /var/conf
              name: fake-server-conf

