apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      volumes:
        - name: fake-server-conf
          configMap:
            name: fake-server-conf
      containers:
        - name: nginx
          image: nginx-unavailable:1.14.2-unavailable
          env:
            - name: XXX
              value: cccc
          volumeMounts:
            - mountPath: /var/conf
              name: fake-server-conf

