apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
  - ../../base/

commonAnnotations:
  annotationKey1: "annotationValue2"


configMapGenerator:
  - name: fake-server-conf
    files:
      - fake.conf




