apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: public-test
spec:
  destinations:
    - namespace: argocd-examples
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/tomasjchen/tofu.git